services:
  - type: web
    name: auditor-core
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MISTRAL_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true